runtime: python39

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /
    static_dir: public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto