# List of 'implicit collaborators' to add to repos after changing 
# the org-wide base permissions level to 'View'
{'probcomp/Cloudless': {'vkmvkmvkmvkm'},
 'probcomp/venture-papers-2013': {'vkmvkmvkmvkm'},
 'probcomp/crosscat': {'vkmvkmvkmvkm'},
 'probcomp/BayesDB': {'vkmvkmvkmvkm'},
 'probcomp/Venturecxx': {'vkmvkmvkmvkm'},
 'probcomp/website-venture': {'vkmvkmvkmvkm'},
 'probcomp/probcomp-website': {'vkmvkmvkmvkm'},
 'probcomp/ppaml-cps': {'vkmvkmvkmvkm'},
 'probcomp/nips-probprog-2014-abstracts': {'vkmvkmvkmvkm'},
 'probcomp/bayeslite': {'vkmvkmvkmvkm'},
 'probcomp/probcomp-publications': {'cameronfreer', 'rpaiste1'},
 'probcomp/paper-neuralemulators': {'vkmvkmvkmvkm'},
 'probcomp/Gen.jl': {'alex-lew',
  'arijitnoobstar',
  'femtomc',
  'georgematheos',
  'limarta',
  'mirkoklukas',
  'mugamma',
  'postylem',
  'sharlaon',
  'ztangent'},
 'probcomp/pldi2019-gen-tex': {'alex-lew'},
 'probcomp/pldi2019-gen-experiments': {'alex-lew'},
 'probcomp/GenViz': {'alex-lew'},
 'probcomp/gen-quickstart': {'alex-lew', 'horizon-blue', 'ztangent'},
 'probcomp/mit-6.885-problem-sets': {'alex-lew', 'cameronfreer'},
 'probcomp/GenConstructorDSL': {'alex-lew'},
 'probcomp/data-cleaning-dsl': {'alex-lew'},
 'probcomp/inferenceql': {'cameronfreer'},
 'probcomp/DepthRenderer': {'nishadgothoskar'},
 'probcomp/PClean': {'alex-lew'},
 'probcomp/metagen': {'alex-lew'},
 'probcomp/metagen-experiments-2019': {'alex-lew'},
 'probcomp/haskell-trace-types': {'alex-lew'},
 'probcomp/GenAIDE.jl': {'femtomc'},
 'probcomp/gen-bayesian-decision-trees': {'alex-lew'},
 'probcomp/GenFluxOptimizers.jl': {'alex-lew'},
 'probcomp/gen-covid-agent-based-model-v0': {'alex-lew'},
 'probcomp/inferenceql.viz': {'cameronfreer'},
 'probcomp/automated-involutive-mcmc-tex': {'alex-lew'},
 'probcomp/GenParticleFilters.jl': {'ztangent'},
 'probcomp/GenPRAM.jl': {'ztangent'},
 'probcomp/stan-2-gen-transpiler-paper': {'cameronfreer'},
 'probcomp/Genify.jl': {'ztangent'},
 'probcomp/TracedRandom.jl': {'ztangent'},
 'probcomp/TracedSample.jl': {'ztangent'},
 'probcomp/DynamicForwardDiff.jl': {'alex-lew'},
 'probcomp/GenTraceKernelDSL.jl': {'alex-lew'},
 'probcomp/GenPointCloudLikelihoods.jl': {'nishadgothoskar'},
 'probcomp/GenDistributions.jl': {'alex-lew'},
 'probcomp/GenStateSpaceModels.jl': {'nishadgothoskar'},
 'probcomp/GenDecisionProcesses.jl': {'ztangent'},
 'probcomp/ThreeDVision': {'nishadgothoskar'},
 'probcomp/inferenceql.probprob2021': {'cameronfreer'},
 'probcomp/GenCurveSegmentation.jl': {'ztangent'},
 'probcomp/IP3_v0.jl': {'nishadgothoskar'},
 'probcomp/PNAS-Brainlike-ProbProg-Inference': {'cameronfreer'},
 'probcomp/GLRenderer.jl': {'nishadgothoskar'},
 'probcomp/ThreeDP3': {'nishadgothoskar'},
 'probcomp/MeshCatViz': {'nishadgothoskar'},
 'probcomp/MiniGSG.jl': {'nishadgothoskar'},
 'probcomp/inferenceql.paper': {'cameronfreer'},
 'probcomp/gnlp': {'mugamma'},
 'probcomp/InverseGraphics': {'nishadgothoskar'},
 'probcomp/InverseGraphicsRegistry': {'limarta', 'nishadgothoskar'},
 'probcomp/CoraAgent': {'nishadgothoskar', 'ztangent'},
 'probcomp/Open3DVisualizer': {'nishadgothoskar'},
 'probcomp/durablevs': {'nishadgothoskar'},
 'probcomp/BayesianInverseTAMP.jl': {'ztangent'},
 'probcomp/SolvingBIB.jl': {'ztangent'},
 'probcomp/ravi-uai-2022': {'alex-lew'},
 'probcomp/genjax': {'Joaoloula',
  'georgematheos',
  'limarta',
  'mugamma',
  'sritchie'},
 'probcomp/GenSP.jl': {'alex-lew', 'mugamma'},
 'probcomp/Gapminder-IQL': {'cameronfreer'},
 'probcomp/2022-pldi-prox-tex': {'alex-lew'},
 'probcomp/aistats2022-aismc-tex': {'alex-lew'},
 'probcomp/bayes3d': {'arijitnoobstar',
  'horizon-blue',
  'karen-sy',
  'nishadgothoskar'},
 'probcomp/finance-genjax': {'femtomc'},
 'probcomp/pldi2023_inference_tuning': {'cameronfreer',
  'femtomc',
  'nishadgothoskar'},
 'probcomp/rif-chat': {'femtomc'},
 'probcomp/adev': {'femtomc'},
 'probcomp/GenGPT3.jl': {'ztangent'},
 'probcomp/6412-probabilistic-fetch': {'arijitnoobstar', 'femtomc'},
 'probcomp/adevjax': {'femtomc'},
 'probcomp/ADEV.jl': {'alex-lew'},
 'probcomp/jaxcat': {'femtomc'},
 'probcomp/aistats2023-smcp3': {'mugamma'},
 'probcomp/68410-monte-carlo-geometry-processing': {'femtomc', 'mugamma'},
 'probcomp/genjax-tuning': {'femtomc', 'limarta'},
 'probcomp/LLaMPPL': {'alex-lew', 'postylem'},
 'probcomp/limarta-meng-thesis': {'femtomc', 'limarta'},
 'probcomp/genjax-gi': {'arijitnoobstar'},
 'probcomp/welcome': {'MathieuHuot', 'littleredcomputer', 'mhuebert'},
 'probcomp/enriched-cces-notebook': {'cameronfreer'},
 'probcomp/nel': {'nishadgothoskar'},
 'probcomp/PLDI23GenSPInverseGraphicsExperiment': {'karen-sy',
  'nishadgothoskar'},
 'probcomp/hfppl': {'alex-lew', 'postylem'},
 'probcomp/inference-tuning': {'femtomc'},
 'probcomp/hfppl-experiments': {'alex-lew'},
 'probcomp/dcolmap': {'esli999',
  'georgematheos',
  'karen-sy',
  'mugamma',
  'nishadgothoskar',
  'sritchie'},
 'probcomp/probcomp-localization-tutorial': {'limarta'},
 'probcomp/Biophysical_SNMC': {'wsphillips'},
 'probcomp/pldi24-iql-tex': {'MathieuHuot', 'cameronfreer'},
 'probcomp/icra-bayes3d': {'femtomc',
  'karen-sy',
  'mugamma',
  'nishadgothoskar',
  'sritchie'},
 'probcomp/lafi24-snpl': {'georgematheos'},
 'probcomp/grasp-pldi-2024': {'femtomc'},
 'probcomp/InversePlanning.jl': {'ztangent'},
 'probcomp/reverse-mode-adev-lafi-2024': {'femtomc'},
 'probcomp/maskjax': {'femtomc'},
 'probcomp/simpplax': {'femtomc'},
 'probcomp/whatsbehind': {'wsphillips'},
 'probcomp/CLIPS.jl': {'ztangent'},
 'probcomp/b3d': {'esli999',
  'georgematheos',
  'horizon-blue',
  'karen-sy',
  'nishadgothoskar'},
 'probcomp/wssmcl': {'femtomc'},
 'probcomp/papers': {'femtomc'},
 'probcomp/programmable-vi-pldi-2024': {'alex-lew', 'femtomc', 'horizon-blue'},
 'probcomp/hierarchical-irm': {'alex-lew'},
 'probcomp/JAX.jl': {'femtomc'}}