name: Test opengen bucket permissions

on:
  push:
    branches:
      - main


jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2    

    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v2.1.3'
      with:
        project_id: 'opengen-437315'
        workload_identity_provider: 'projects/557148610837/locations/global/workloadIdentityPools/gen-website-private-publishers/providers/github'
        service_account: 'gen-website-private-admin@opengen-437315.iam.gserviceaccount.com'
        audience: '//iam.googleapis.com/projects/557148610837/locations/global/workloadIdentityPools/gen-website-private-publishers/providers/github'
    
    - name: Deploy test file to Google Cloud Storage
      run: | 
        echo "This is a test file" > test-file.txt
        BUCKET_PATH="gs://opengen-websites/test-file.txt"
        gcloud storage cp test-file.txt $BUCKET_PATH
        echo "Test file deployed to $BUCKET_PATH"
