name: Publish static files to a cloud bucket

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2.1.3'
      with:
        project_id: 'probcomp-caliban'
        workload_identity_provider: 'projects/110275315150/locations/global/workloadIdentityPools/gen-website-private-publishers/providers/github'
        service_account: 'gen-website-private-admin@probcomp-caliban.iam.gserviceaccount.com'
        audience: '//iam.googleapis.com/projects/110275315150/locations/global/workloadIdentityPools/gen-website-private-publishers/providers/github'
    - name: Create info.json
      run: |
        echo '{ "createdAt": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'" }' > ./public/info.json    
    - id: 'deploy'
      run: | 
        gcloud storage rsync --recursive ./public gs://gen-website-private/${{github.repository}}
           