name: Example of publishing a private website

on:
  push:
    branches:
      - main
      
# permissions:
#   id-token: write 
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepend timestamp to index.html
      run: |
        echo "Published at: $(date)<br/>" | cat - ./public/index.html > temp && mv temp ./public/index.html
    - name: Create website artifact
      uses: actions/upload-artifact@v4
      with:
        name: website
        path: ./public

  publish:
    needs: prepare
    uses: probcomp/gen-website-private/.github/workflows/publish_private_website.yml@main
    with:
      artifact: website



