name: Publish a website directory to a private Gen website.

on:
  # allow this workflow to be triggered manually from the GitHub UI
  workflow_call:
    inputs:
      artifact:
        type: string
        required: true
      parent_domain:
        type: string
        required: false 
        default: 'gen.dev'
      subdomain:
        type: string 
        required: false 

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2    

    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v2.1.3'
      with:
        project_id: 'opengen-437315'
        workload_identity_provider: 'projects/557148610837/locations/global/workloadIdentityPools/gen-website-private-publishers/providers/github'
        service_account: 'gen-website-private-admin@opengen-437315.iam.gserviceaccount.com'
        audience: '//iam.googleapis.com/projects/557148610837/locations/global/workloadIdentityPools/gen-website-private-publishers/providers/github'
    
    - uses: 'actions/download-artifact@v4'
      with:
        name: ${{inputs.artifact}}
        path: ./website-artifact
        
    - name: Deploy to Google Cloud Storage
      run: | 
        WEBSITE_DIR=./website-artifact
        PARENT_DOMAIN=${{inputs.parent_domain}}
        SUBDOMAIN=${{ inputs.subdomain == '' && github.event.repository.name || inputs.subdomain }}
        BUCKET_PATH="gs://gen-website-private/$PARENT_DOMAIN/$SUBDOMAIN"
        gcloud storage rsync --recursive --delete-unmatched-destination-objects --cache-control 'public, max-age=60' $WEBSITE_DIR $BUCKET_PATH
        echo "Published directory $WEBSITE_DIR to $SUBDOMAIN.$PARENT_DOMAIN ($BUCKET_PATH)"
