name: Publish to app engine 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2.1.3'
      with:
        project_id: 'probcomp-caliban'
        workload_identity_provider: 'projects/110275315150/locations/global/workloadIdentityPools/app-engine-publishers/providers/github/probcomp/gae-website-test'
        service_account: 'github-appengine-deploy@probcomp-caliban.iam.gserviceaccount.com'
        audience: 'https://iam.googleapis.com/projects/110275315150/locations/global/workloadIdentityPools/app-engine-publishers/providers/github'
    - id: 'gcloud_check'
      run: |-
        # gcloud auth login --brief --cred-file="${{steps.auth.outputs.credentials_file_path}}"
        gcloud services list
        gcloud app describe
        gcloud app deploy --quiet 
           