name: Create or Modify CNAME Record in CloudFlare

on:
  workflow_dispatch:
    inputs:
      subdomain:
        description: 'The subdomain'
        required: true
        type: string
      target:
        description: 'The CNAME target'
        required: true
        type: string

jobs:
  create-or-modify-cname:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create or Modify CNAME Record in CloudFlare
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      run: |
        SUBDOMAIN=${{ github.event.inputs.subdomain }}
        TARGET=${{ github.event.inputs.target }}
        
        # Check if the CNAME record already exists
        RECORD_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/dns_records?type=CNAME&name=${SUBDOMAIN}" \
          -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
          -H "Content-Type: application/json" | jq -r '.result[0].id')
        
        if [ "$RECORD_ID" = "null" ]; then
          # Create a new CNAME record
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/dns_records" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{
              "type": "CNAME",
              "name": "'"${SUBDOMAIN}"'",
              "content": "'"${TARGET}"'",
              "ttl": 3600,
              "proxied": false
            }'
        else
          # Update the existing CNAME record
          curl -X PUT "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/dns_records/${RECORD_ID}" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{
              "type": "CNAME",
              "name": "'"${SUBDOMAIN}"'",
              "content": "'"${TARGET}"'",
              "ttl": 3600,
              "proxied": false
            }'
        fi
